apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-location-service-grpc
  name: udaconnect-api-location-service-grpc
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30003
  selector:
    service: udaconnect-api-location-service-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-location-service-grpc
  name: udaconnect-api-location-service-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-location-service-grpc
  template:
    metadata:
      labels:
        service: udaconnect-api-location-service-grpc
    spec:
      containers:
      - image: vahiwe/api-location-service:grpc
        name: udaconnect-api-location-service-grpc
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_TOPIC
          value: test
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_HOST
          value: my-cluster-kafka-bootstrap.my-kafka-project.svc.cluster.local
      restartPolicy: Always
